add logging for all program functions

diff --git a/main b/main
--- a/main
+++ b/main
@@ -2,7 +2,7 @@
 
 ## Just Another Yogourt
 
-ver="7.3.0"; rc="pre_release-1"; cdname="Cheesecake"
+ver="7.3.01"; rc="pre_release-1"; cdname="Cheesecake"
 
 set -o pipefail
 REAL_HOME=$(getent passwd "${SUDO_USER:-$USER}" 2>/dev/null | cut -d: -f6); REAL_HOME=${REAL_HOME:-$HOME}
@@ -11,7 +11,7 @@ LANG_FOLDER="/usr/share/jay"
 BACKUP_DIR="$CFG_FOLDER/backup"; BACKUP_FILE="$BACKUP_DIR/backup.txt"
 LOG_FILE="$REAL_HOME/.cache/jay.log"
 CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'; BOLD='\033[1m'
-ALERT="[!]"; ERROR="[ERROR]"; COMPLETE="[OK]"; NOTE="[*]"; CC="::"
+ALERT="[!]"; ERROR="[ERROR]"; COMPLETE="[✓]"; NOTE="[*]"; CC=" ::"
 
 detback() {
     for b in yay paru; do
@@ -127,14 +127,17 @@ proc_func() {
             [[ ! -s "$LOG_FILE" ]] && echo -e "${YELLOW}$NOTE $M_EMPTY_LOG" && exit 0
             if [[ -n "$log_lines" && "$log_lines" =~ ^[0-9]+$ ]]; then
                 tail -n "$log_lines" "$LOG_FILE"
+                exit 0
             else
                 cat "$LOG_FILE"
+                exit 0
             fi
         ;;
         cl)
             [[ ! -s "$LOG_FILE" ]] && echo "$NOTE $M_EMPTY_LOG" && exit 0
             : > "$LOG_FILE"
             sc "$M_DONE"
+            exit 0
         ;;
         *)
             err "var func not defined"
@@ -253,6 +256,7 @@ help_message() {
     exit 0
 }
 chmgr() {
+    log_type="1" && mklog "-Sc" "clean-cache"
     local cache_dir="$REAL_HOME/.cache/$backend"
     if [[ -d "$cache_dir" ]]; then
         st "$M_CACHE_CLEANING_BUILDS"
@@ -266,9 +270,10 @@ chmgr() {
     fi
     st "$M_CACHE_CLEANING_PACMAN"
     cmd="-Sc"
-    tag="CLEANED CACHE"
+    tag="Wiped cache"
 }
 rmorps() {
+    log_type="1" && mklog "-Qtqd" "remove-orphans"
     st "$M_ORPHANS_SEARCHING"
     mapfile -t final_args < <("$backend" -Qqtd 2>/dev/null)
     orphans_n=${#final_args[@]}
@@ -279,7 +284,9 @@ rmorps() {
     cmd="-Rsn"
     tag="REMOVED ORPHANS"
 }
+
 ckconf() {
+    log_type="1" && mklog "pacnews" "conf-merge" "0"
     st "$M_CONF_SEARCHING"
     local pacnews=$(find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2>/dev/null)
     if [[ -z "$pacnews" ]]; then sc "$M_CONF_NONE"; else
@@ -293,6 +300,7 @@ ckconf() {
     tag="CLEAR DIFFS"
 }
 mksnap() {
+    log_type="1" && mklog "timeshift" "System snapshot" "0"
     if [[ "$dry_run" == "1" ]]; then
         echo -e "${CYAN}[DRY RUN] Would run:${NC} sudo timeshift --create --comments \"JAY Auto-Snapshot\" --tags D"
         return
@@ -311,6 +319,7 @@ mksnap() {
 }
 
 pin() {
+    log_type="1" && mklog "pin" "pin a package" "0"
     local pkg="${final_args[0]}"
     local conf="/etc/pacman.conf"
     [[ -z "$pkg" ]] && error "$M_DEPS_SPECIFY"
@@ -341,6 +350,7 @@ pin() {
 }
 
 depends() {
+    log_type="1" && mklog "pactree" "Check for dependencies" "0"
     ! command -v pactree &>/dev/null && { st "$M_INSTALL_CONTRIB pacman-contrib..."; "$backend" -S pacman-contrib --noconfirm; }
     local pkg="${final_args[0]}"
     [[ -z "$pkg" ]] && echo "$ALERT $M_DEPS_SPECIFY" && exit 1
@@ -400,6 +410,7 @@ show_stats() {
 }
 
 view_pkgbuild() {
+    log_type="1" && mklog "-Gp" "View PKGBUILD file"
     [[ "$backend" == "pacman" ]] && err "$E_08"
     local pkg="$1"
     [[ -z $pkg ]] && echo "$NOTE $M_PKGB_SPECIFY" && exit 1
@@ -417,6 +428,7 @@ view_pkgbuild() {
 }
 
 ls_aur() {
+    log_type="1" && mklog "-Qqm" "List AUR packages"
     [[ "$backend" == "pacman" ]] && err "$E_08"
     st "$M_AUR_FILTERING"
     local pkgs; pkgs=$("$backend" -Qqm)
@@ -428,6 +440,7 @@ ls_aur() {
 
 refresh_mirrors() {
     ntest
+    log_type="1" && mklog "reflector" "Refresh mirrors"
     st "$M_MIRROR_START"
     if ! command -v reflector &>/dev/null; then
         echo -e "${YELLOW}$NOTE $M_REFLECTOR_NOT_FOUND${NC}"
@@ -462,8 +475,9 @@ refresh_mirrors() {
 }
 
 fix_keys() {
+    log_type="1" && mklog "gpg" "Recovery gpg keys"
     st "$M_GPG_START"
-    "$backend" -S archlinux-keyring --noconfirm --needed 2>&1 | tee "$tmp_out"
+    if ! yay -Qs archlinux-keyring; then "$backend" -S archlinux-keyring --noconfirm --needed 2>&1 | tee "$tmp_out"; fi
     if [[ -f "$tmp_out" ]]; then
         local keys=$(grep -oP '(?<=key\s)([A-F0-9]{16,})|(?<=ID\s)([A-F0-9]{16,})' "$tmp_out" | sort -u)
         if [[ -n "$keys" ]]; then
@@ -481,6 +495,7 @@ fix_keys() {
 }
 
 backup_func() {
+    log_type="1" && mklog "backup" "Create / restore backups" "0"
     case "$backup_action" in
         "create")
             st "Creating backup of packages..."
@@ -550,12 +565,15 @@ mklog() {
     local tag="$1"
     local info="$2"
     printf -v date_str '%(%Y-%m-%d - %H:%M:%S)T' -1
-    echo "[$date_str] $tag -> $backend $cmd ${final_args[@]} ${yay_flags[@]}; used flatpak = $used_flat - Exit Status $status" >> "$LOG_FILE"
+    [[ -z "${final_args[@]}" ]] && proc_args="" || proc_args="${final_args[@]}"
+    [[ -z "${yay_flags[@]}" ]] && proc_args="" || proc_args="${yay_flags[@]}"
+    echo "[$date_str] $tag -> $backend $cmd $proc_args; used flatpak = $used_flat - Exit Status $status" >> "$LOG_FILE"
     echo " " >> "$LOG_FILE"
 }
 
 check_updates() {
     ntest
+    log_type="1" && mklog "-Qua" "Search for updates"
     [[ "$backend" == "pacman" ]] && return 0
     if "$backend" -Qua 2>/dev/null | grep -qi "jay-bin"; then
         echo -e "$M_JAY_UPD_FOUND"
@@ -603,6 +621,7 @@ check_updates() {
     mklog "FOUND UPDATES" "$total updates (Flatpak: $flat)"
 }
 get_package_path() {
+    log_type="1" && mklog "-Ql" "get package path"
     local pkg="$1"
     local bins=$(pacman -Ql "$pkg" 2>/dev/null | awk '/\/bin\// {print $2}')
     if [[ -n "$bins" ]]; then
